package vercel

import mcp "github.com/daltoniam/switchboard"

var tools = []mcp.ToolDefinition{
	{
		Name:        mcp.ToolName("vercel_list_teams"),
		Description: "List Vercel teams and workspaces available to the token. Start here to discover team_id or team_slug for scoped project, deployment, domain, and environment workflows.",
		Parameters: map[string]string{
			"limit": "Results per page (default 20)",
			"next":  "Pagination cursor from previous response",
			"since": "Lower timestamp cursor/filter in milliseconds",
			"until": "Upper timestamp cursor/filter in milliseconds",
		},
	},
	{
		Name:        mcp.ToolName("vercel_get_team"),
		Description: "Get details for a Vercel team or workspace. Use after vercel_list_teams.",
		Parameters:  map[string]string{"team_id": "Team identifier (team_...)", "team_slug": "Team URL slug if team_id is not known"},
	},
	{
		Name:        mcp.ToolName("vercel_list_team_members"),
		Description: "List Vercel team members and roles. Use after vercel_list_teams to inspect workspace access.",
		Parameters: map[string]string{
			"team_id":   "Team identifier (defaults to configured team_id)",
			"team_slug": "Team slug (defaults to configured team_slug when team_id is empty)",
			"limit":     "Results per page (default 20)",
			"next":      "Pagination cursor from previous response",
			"search":    "Search by name, username, or email",
			"role":      "Filter by team role",
		},
	},
	{
		Name:        mcp.ToolName("vercel_list_user_events"),
		Description: "List Vercel audit and activity events such as deployments, login activity, and team changes.",
		Parameters: map[string]string{
			"team_id":      "Team identifier (defaults to configured team_id)",
			"team_slug":    "Team slug (defaults to configured team_slug when team_id is empty)",
			"limit":        "Results per page (default 20)",
			"next":         "Pagination cursor from previous response",
			"since":        "Lower timestamp cursor/filter in milliseconds",
			"until":        "Upper timestamp cursor/filter in milliseconds",
			"types":        "Comma-separated event types",
			"project_ids":  "Comma-separated project IDs",
			"principal_id": "User or team principal ID",
			"with_payload": "Include event payload details (true/false)",
		},
	},
	{
		Name:        mcp.ToolName("vercel_list_projects"),
		Description: "List Vercel projects, apps, frontend sites, and repositories. Start here for deployment, environment variable, domain, and alias workflows.",
		Parameters: map[string]string{
			"team_id":   "Team identifier (defaults to configured team_id)",
			"team_slug": "Team slug (defaults to configured team_slug when team_id is empty)",
			"limit":     "Results per page (default 20)",
			"next":      "Pagination cursor from previous response",
			"search":    "Search projects by name",
		},
	},
	{
		Name:        mcp.ToolName("vercel_get_project"),
		Description: "Get Vercel project details including framework, repository linkage, targets, and configuration. Use after vercel_list_projects.",
		Parameters: map[string]string{
			"id_or_name": "Project ID or name",
			"team_id":    "Team identifier (defaults to configured team_id)",
			"team_slug":  "Team slug (defaults to configured team_slug when team_id is empty)",
		},
		Required: []string{"id_or_name"},
	},
	{
		Name:        mcp.ToolName("vercel_create_project"),
		Description: "Create a Vercel project. Provide body with project settings such as name, framework, gitRepository, buildCommand, outputDirectory, and installCommand.",
		Parameters: map[string]string{
			"team_id":   "Team identifier (defaults to configured team_id)",
			"team_slug": "Team slug (defaults to configured team_slug when team_id is empty)",
			"body":      "Project create request object",
		},
		Required: []string{"body"},
	},
	{
		Name:        mcp.ToolName("vercel_update_project"),
		Description: "Update Vercel project settings. Use after vercel_get_project to modify build, framework, command, or environment configuration.",
		Parameters: map[string]string{
			"id_or_name": "Project ID or name",
			"team_id":    "Team identifier (defaults to configured team_id)",
			"team_slug":  "Team slug (defaults to configured team_slug when team_id is empty)",
			"body":       "Project update request object",
		},
		Required: []string{"id_or_name", "body"},
	},
	{
		Name:        mcp.ToolName("vercel_delete_project"),
		Description: "Delete a Vercel project. Use after vercel_list_projects or vercel_get_project when removing an app/site.",
		Parameters: map[string]string{
			"id_or_name": "Project ID or name",
			"team_id":    "Team identifier (defaults to configured team_id)",
			"team_slug":  "Team slug (defaults to configured team_slug when team_id is empty)",
		},
		Required: []string{"id_or_name"},
	},
	{
		Name:        mcp.ToolName("vercel_list_deployments"),
		Description: "List Vercel deployments, deploy history, build status, preview URLs, production rollouts, and failed deploys. Start here for CI/CD deployment debugging.",
		Parameters: map[string]string{
			"team_id":    "Team identifier (defaults to configured team_id)",
			"team_slug":  "Team slug (defaults to configured team_slug when team_id is empty)",
			"limit":      "Results per page (default 20)",
			"next":       "Pagination cursor from previous response",
			"since":      "Lower timestamp cursor/filter in milliseconds",
			"until":      "Upper timestamp cursor/filter in milliseconds",
			"project_id": "Project ID filter",
			"app":        "Project/app name filter",
			"state":      "Deployment state: BUILDING, ERROR, READY, CANCELED, QUEUED, INITIALIZING",
			"target":     "Deployment target: production, preview, or staging",
		},
	},
	{
		Name:        mcp.ToolName("vercel_get_deployment"),
		Description: "Get details for a specific Vercel deployment including state, URL, git source, target, and build metadata. Use after vercel_list_deployments.",
		Parameters: map[string]string{
			"deployment_id": "Deployment ID (dpl_...)",
			"team_id":       "Team identifier (defaults to configured team_id)",
			"team_slug":     "Team slug (defaults to configured team_slug when team_id is empty)",
		},
		Required: []string{"deployment_id"},
	},
	{
		Name:        mcp.ToolName("vercel_create_deployment"),
		Description: "Create or redeploy a Vercel deployment. Provide body with name, files, gitMetadata, projectSettings, target, deploymentId, or withLatestCommit.",
		Parameters: map[string]string{
			"team_id":   "Team identifier (defaults to configured team_id)",
			"team_slug": "Team slug (defaults to configured team_slug when team_id is empty)",
			"body":      "Deployment create request object",
			"force_new": "Force new deployment instead of reusing build cache (true/false)",
		},
		Required: []string{"body"},
	},
	{
		Name:        mcp.ToolName("vercel_cancel_deployment"),
		Description: "Cancel a queued or building Vercel deployment. Use after vercel_list_deployments when a build is stuck or no longer needed.",
		Parameters: map[string]string{
			"deployment_id": "Deployment ID (dpl_...)",
			"team_id":       "Team identifier (defaults to configured team_id)",
			"team_slug":     "Team slug (defaults to configured team_slug when team_id is empty)",
		},
		Required: []string{"deployment_id"},
	},
	{
		Name:        mcp.ToolName("vercel_delete_deployment"),
		Description: "Delete a Vercel deployment. Use after vercel_list_deployments to remove old preview or failed deployments.",
		Parameters: map[string]string{
			"deployment_id": "Deployment ID (dpl_...)",
			"url":           "Deployment URL alternative identifier",
			"team_id":       "Team identifier (defaults to configured team_id)",
			"team_slug":     "Team slug (defaults to configured team_slug when team_id is empty)",
		},
		Required: []string{"deployment_id"},
	},
	{
		Name:        mcp.ToolName("vercel_list_deployment_events"),
		Description: "List Vercel deployment build events and logs. Use after vercel_list_deployments or vercel_get_deployment to debug build errors and failed deploys.",
		Parameters: map[string]string{
			"deployment_id_or_url": "Deployment ID or URL",
			"team_id":              "Team identifier (defaults to configured team_id)",
			"team_slug":            "Team slug (defaults to configured team_slug when team_id is empty)",
			"limit":                "Results per page (default 100)",
			"since":                "Lower timestamp cursor/filter in milliseconds",
			"until":                "Upper timestamp cursor/filter in milliseconds",
			"direction":            "Log direction: forward or backward",
			"name":                 "Build step name filter",
			"status_code":          "HTTP status code filter",
			"builds":               "Include build logs/events (true/false)",
		},
		Required: []string{"deployment_id_or_url"},
	},
	{
		Name:        mcp.ToolName("vercel_list_runtime_logs"),
		Description: "List Vercel runtime logs for a deployment. Use after vercel_get_deployment to inspect function, edge, and request logs.",
		Parameters: map[string]string{
			"project_id":    "Project ID",
			"deployment_id": "Deployment ID",
			"team_id":       "Team identifier (defaults to configured team_id)",
			"team_slug":     "Team slug (defaults to configured team_slug when team_id is empty)",
			"limit":         "Results per page (default 100)",
			"since":         "Lower timestamp cursor/filter in milliseconds",
			"until":         "Upper timestamp cursor/filter in milliseconds",
			"next":          "Pagination cursor from previous response",
		},
		Required: []string{"project_id", "deployment_id"},
	},
	{
		Name:        mcp.ToolName("vercel_list_project_env_vars"),
		Description: "List Vercel project environment variables and secret metadata. Use after vercel_get_project to inspect production, preview, and development config.",
		Parameters: map[string]string{
			"project_id_or_name": "Project ID or name",
			"team_id":            "Team identifier (defaults to configured team_id)",
			"team_slug":          "Team slug (defaults to configured team_slug when team_id is empty)",
			"limit":              "Results per page (default 20)",
			"next":               "Pagination cursor from previous response",
			"git_branch":         "Filter environment variables by git branch",
			"target":             "Filter by target: production, preview, or development",
		},
		Required: []string{"project_id_or_name"},
	},
	{
		Name:        mcp.ToolName("vercel_create_project_env_vars"),
		Description: "Create one or more Vercel project environment variables. Values are write-only; use after vercel_get_project.",
		Parameters: map[string]string{
			"project_id_or_name": "Project ID or name",
			"team_id":            "Team identifier (defaults to configured team_id)",
			"team_slug":          "Team slug (defaults to configured team_slug when team_id is empty)",
			"envs":               "Array of env var objects with key, value, target, type, gitBranch, comment",
			"upsert":             "Update existing variables with same key/target (true/false)",
		},
		Required: []string{"project_id_or_name", "envs"},
	},
	{
		Name:        mcp.ToolName("vercel_update_project_env_var"),
		Description: "Update a Vercel project environment variable by ID. Use after vercel_list_project_env_vars.",
		Parameters: map[string]string{
			"project_id_or_name": "Project ID or name",
			"env_id":             "Environment variable ID",
			"team_id":            "Team identifier (defaults to configured team_id)",
			"team_slug":          "Team slug (defaults to configured team_slug when team_id is empty)",
			"body":               "Environment variable update object",
		},
		Required: []string{"project_id_or_name", "env_id", "body"},
	},
	{
		Name:        mcp.ToolName("vercel_delete_project_env_var"),
		Description: "Delete a Vercel project environment variable by ID. Use after vercel_list_project_env_vars.",
		Parameters: map[string]string{
			"project_id_or_name": "Project ID or name",
			"env_id":             "Environment variable ID",
			"team_id":            "Team identifier (defaults to configured team_id)",
			"team_slug":          "Team slug (defaults to configured team_slug when team_id is empty)",
		},
		Required: []string{"project_id_or_name", "env_id"},
	},
	{
		Name:        mcp.ToolName("vercel_add_project_domain"),
		Description: "Add a domain to a Vercel project. Use after vercel_get_project when configuring custom domains.",
		Parameters: map[string]string{
			"project_id_or_name": "Project ID or name",
			"domain":             "Domain name to add",
			"team_id":            "Team identifier (defaults to configured team_id)",
			"team_slug":          "Team slug (defaults to configured team_slug when team_id is empty)",
		},
		Required: []string{"project_id_or_name", "domain"},
	},
	{
		Name:        mcp.ToolName("vercel_remove_project_domain"),
		Description: "Remove a domain from a Vercel project. Use after vercel_get_project or vercel_get_domain_config.",
		Parameters: map[string]string{
			"project_id_or_name": "Project ID or name",
			"domain":             "Domain name to remove",
			"team_id":            "Team identifier (defaults to configured team_id)",
			"team_slug":          "Team slug (defaults to configured team_slug when team_id is empty)",
		},
		Required: []string{"project_id_or_name", "domain"},
	},
	{
		Name:        mcp.ToolName("vercel_get_domain_config"),
		Description: "Get Vercel domain DNS configuration and misconfiguration status. Use when debugging custom domain setup.",
		Parameters: map[string]string{
			"domain":             "Domain name",
			"project_id_or_name": "Optional project ID or name for stricter checks",
			"strict":             "Perform strict configuration check (true/false)",
			"team_id":            "Team identifier (defaults to configured team_id)",
			"team_slug":          "Team slug (defaults to configured team_slug when team_id is empty)",
		},
		Required: []string{"domain"},
	},
	{
		Name:        mcp.ToolName("vercel_list_deployment_aliases"),
		Description: "List aliases assigned to a Vercel deployment. Use after vercel_get_deployment to inspect production and preview URLs.",
		Parameters: map[string]string{
			"deployment_id": "Deployment ID (dpl_...)",
			"team_id":       "Team identifier (defaults to configured team_id)",
			"team_slug":     "Team slug (defaults to configured team_slug when team_id is empty)",
		},
		Required: []string{"deployment_id"},
	},
	{
		Name:        mcp.ToolName("vercel_assign_deployment_alias"),
		Description: "Assign a custom alias URL to a Vercel deployment. Use after vercel_get_deployment for manual alias promotion.",
		Parameters: map[string]string{
			"deployment_id": "Deployment ID (dpl_...)",
			"alias":         "Alias domain or URL to assign",
			"team_id":       "Team identifier (defaults to configured team_id)",
			"team_slug":     "Team slug (defaults to configured team_slug when team_id is empty)",
		},
		Required: []string{"deployment_id", "alias"},
	},
	{
		Name:        mcp.ToolName("vercel_delete_deployment_alias"),
		Description: "Delete a Vercel deployment alias by alias ID. Use after vercel_list_deployment_aliases.",
		Parameters: map[string]string{
			"alias_id":  "Alias ID",
			"team_id":   "Team identifier (defaults to configured team_id)",
			"team_slug": "Team slug (defaults to configured team_slug when team_id is empty)",
		},
		Required: []string{"alias_id"},
	},
}
