use std::collections::HashMap;
use switchboard_guest_sdk::ToolDefinition;

macro_rules! tool {
    ($name:expr, $desc:expr, $params:expr) => {
        ToolDefinition { name: $name.into(), description: $desc.into(), parameters: $params, required: vec![] }
    };
    ($name:expr, $desc:expr, $params:expr, $req:expr) => {
        ToolDefinition { name: $name.into(), description: $desc.into(), parameters: $params, required: $req.iter().map(|s: &&str| s.to_string()).collect() }
    };
}

macro_rules! params {
    () => { HashMap::new() };
    ($($k:expr => $v:expr),+ $(,)?) => {{
        let mut m = HashMap::new();
        $(m.insert($k.into(), $v.into());)+
        m
    }};
}

pub fn tool_definitions() -> Vec<ToolDefinition> {
    vec![
        tool!("overmind_list_available_agents", "List all agents available to launch in the current flow. Returns each agent's ID, name, and description.\n\nCall this first to discover which agents you can dispatch with overmind_launch_agent.", params!()),
        tool!("overmind_launch_agent", "Launch a child agent within the current flow. Returns the new AgentRun ID which can be polled for status and results.\n\nThe agent_id is provided in your initial prompt or flow context. Use this to delegate subtasks to specialized agents. The child agent runs in its own Pod with its own MCP integrations.", params!("agent_id" => "The ID of the agent to launch (must be in the flow's available_agent_ids)", "prompt" => "The task prompt to give the child agent", "context" => "Optional additional context or data to pass to the child agent"), &["agent_id", "prompt"]),
        tool!("overmind_get_agent_status", "Check the current status of an agent run. Returns the agent's state (pending, launching, running, completed, failed, recovering, cancelled).\n\nPoll this periodically after launching a child agent to check if it has completed.", params!("agent_run_id" => "The AgentRun ID to check (returned by overmind_launch_agent)"), &["agent_run_id"]),
        tool!("overmind_get_agent_result", "Get the output/result of a completed agent run. Only available after the agent reaches 'completed' state.\n\nUse overmind_get_agent_status first to verify the agent has completed before calling this.", params!("agent_run_id" => "The AgentRun ID to get results for"), &["agent_run_id"]),
        tool!("overmind_complete_flow", "Signal that the current flow is complete. This marks the flow as finished and triggers cleanup of all running agent Pods. The calling agent's identity is injected automatically.\n\nCall this when all work is done and results have been collected. After calling this, no further agent launches or tool calls should be made.", params!("summary" => "A brief summary of the flow's outcome", "status" => "The completion status: 'success' or 'failure' (default: 'success')"), &["summary"]),
        tool!("overmind_list_agents", "List all agent definitions in overmind. Start here to discover available agents, their models, prompts, and MCP role assignments.", params!()),
        tool!("overmind_get_agent", "Get an agent definition by ID. Returns name, model, model_provider, base_prompt, mcp_role_id, and description. Use after list_agents.", params!("id" => "Agent ID (UUID)"), &["id"]),
        tool!("overmind_create_agent", "Create a new agent definition. Agents are AI workers with a model, prompt, and MCP role that determines which integrations and tools they can access.", params!("name" => "Unique agent name", "description" => "Human-readable description of the agent's purpose", "model" => "LLM model name (e.g. claude-sonnet-4-20250514)", "model_provider" => "Model provider (e.g. anthropic, openai)", "base_prompt" => "System prompt for the agent", "mcp_role_id" => "MCP role ID that controls which integrations/tools this agent can access"), &["name"]),
        tool!("overmind_update_agent", "Update an existing agent definition. Use after get_agent to modify name, model, prompt, or role assignment.", params!("id" => "Agent ID (UUID)", "name" => "Agent name", "description" => "Human-readable description", "model" => "LLM model name", "model_provider" => "Model provider", "base_prompt" => "System prompt", "mcp_role_id" => "MCP role ID"), &["id"]),
        tool!("overmind_delete_agent", "Delete an agent definition. Fails if the agent is referenced by active flows.", params!("id" => "Agent ID (UUID)"), &["id"]),
        tool!("overmind_list_flows", "List all flow definitions. Flows are orchestrated multi-agent pipelines with a prompt template, available agents, and webhook configuration. Start here for flow management.", params!()),
        tool!("overmind_get_flow", "Get a flow definition by ID. Returns name, prompt_template, available agents, webhook config, repo_url, and timeout. Use expand=agents to include agent details.", params!("id" => "Flow ID (UUID)", "expand" => "Set to 'agents' to include agent details in the response"), &["id"]),
        tool!("overmind_create_flow", "Create a new flow definition. A flow orchestrates multiple agents with a prompt template, webhook triggers, and output configuration.", params!("name" => "Unique flow name", "description" => "Human-readable description", "prompt_template" => "Go template for the flow prompt (rendered with webhook params)", "initial_agent_id" => "ID of the first agent to run when the flow starts", "available_agent_ids" => "JSON array of agent IDs that can be launched within this flow", "repo_url" => "Git repository URL for the flow's code", "repo_ref" => "Git ref (branch/tag) to check out", "timeout_minutes" => "Maximum flow duration in minutes", "enabled" => "Whether the flow accepts triggers (default: false)", "output_webhook_url" => "URL to POST flow results to on completion", "output_webhook_template" => "Go template for the output webhook body", "webhook_secret" => "HMAC secret for validating inbound webhook triggers"), &["name"]),
        tool!("overmind_update_flow", "Update an existing flow definition. Use after get_flow.", params!("id" => "Flow ID (UUID)", "name" => "Flow name", "description" => "Human-readable description", "prompt_template" => "Go template for the flow prompt", "initial_agent_id" => "ID of the first agent to run", "available_agent_ids" => "JSON array of agent IDs available in this flow", "repo_url" => "Git repository URL", "repo_ref" => "Git ref (branch/tag)", "timeout_minutes" => "Maximum flow duration in minutes", "enabled" => "Whether the flow accepts triggers", "output_webhook_url" => "URL to POST flow results to", "output_webhook_template" => "Go template for the output webhook body", "webhook_secret" => "HMAC secret for webhook triggers"), &["id"]),
        tool!("overmind_delete_flow", "Delete a flow definition. Fails if the flow has active runs.", params!("id" => "Flow ID (UUID)"), &["id"]),
        tool!("overmind_clone_flow", "Clone an existing flow, creating a copy with a new name. Duplicates all settings including agent assignments.", params!("id" => "Flow ID (UUID) to clone", "name" => "Name for the cloned flow (optional, defaults to 'Copy of <original>')"), &["id"]),
        tool!("overmind_run_flow", "Trigger a flow run directly with a prompt or template parameters. Returns the flow_run_id and initial_agent_run_id. Use after get_flow.", params!("id" => "Flow ID (UUID) to run", "prompt" => "Direct prompt text (used if no prompt_template is set on the flow)", "params" => "JSON object of template parameters (used to render prompt_template)"), &["id"]),
        tool!("overmind_validate_flow", "Validate a flow definition without creating it. Returns validation errors if the flow configuration is invalid.", params!("name" => "Flow name", "description" => "Human-readable description", "prompt_template" => "Go template for the flow prompt", "initial_agent_id" => "ID of the first agent to run", "available_agent_ids" => "JSON array of agent IDs", "repo_url" => "Git repository URL", "repo_ref" => "Git ref (branch/tag)", "timeout_minutes" => "Maximum flow duration in minutes", "enabled" => "Whether the flow accepts triggers", "output_webhook_url" => "Output webhook URL", "output_webhook_template" => "Output webhook body template", "webhook_secret" => "HMAC secret for webhook triggers")),
        tool!("overmind_list_flow_runs", "List runs for a flow. Returns run ID, state (pending, running, completed, failed, cancelled), timestamps, and rendered prompt. Start here to monitor flow execution.", params!("flow_id" => "Flow ID (UUID) to list runs for"), &["flow_id"]),
        tool!("overmind_get_flow_run", "Get a flow run by ID with its agent runs. Returns state, rendered prompt, output, and all child agent runs. Use after list_flow_runs.", params!("id" => "Flow Run ID (UUID)"), &["id"]),
        tool!("overmind_cancel_flow_run", "Cancel a running flow. Marks the flow run and all active agent runs as cancelled.", params!("id" => "Flow Run ID (UUID)"), &["id"]),
        tool!("overmind_list_agent_runs", "List agent runs for a flow run. Returns agent_id, state, attempt count, timestamps, and worker assignment. Use after get_flow_run for more detail on individual agents.", params!("flow_run_id" => "Flow Run ID (UUID)"), &["flow_run_id"]),
        tool!("overmind_get_agent_run", "Get an agent run by ID with session messages. Returns full execution detail including state, output, heartbeat, pod_name, and conversation history.", params!("id" => "Agent Run ID (UUID)"), &["id"]),
        tool!("overmind_list_mcp_identities", "List all MCP identities. Identities store encrypted credentials for a specific integration (e.g. GitHub token, Slack token). Start here for credential management.", params!()),
        tool!("overmind_get_mcp_identity", "Get an MCP identity by ID. Returns name, integration_name, and masked credentials. Use after list_mcp_identities.", params!("id" => "MCP Identity ID (UUID)"), &["id"]),
        tool!("overmind_create_mcp_identity", "Create an MCP identity with encrypted credentials for an integration. Used in MCP role entries to grant agents access to specific integrations.", params!("name" => "Unique identity name", "integration_name" => "Integration this identity authenticates (e.g. github, slack, datadog)", "credentials" => "JSON object of credential key-value pairs for the integration"), &["name", "integration_name", "credentials"]),
        tool!("overmind_update_mcp_identity", "Update an MCP identity's name, integration, or credentials. Use after get_mcp_identity.", params!("id" => "MCP Identity ID (UUID)", "name" => "Identity name", "integration_name" => "Integration name", "credentials" => "JSON object of credential key-value pairs"), &["id"]),
        tool!("overmind_delete_mcp_identity", "Delete an MCP identity. Fails if referenced by MCP role entries.", params!("id" => "MCP Identity ID (UUID)"), &["id"]),
        tool!("overmind_list_mcp_roles", "List all MCP roles. Roles group MCP identities with tool glob patterns to control which integrations and tools an agent can access. Start here for access control management.", params!()),
        tool!("overmind_get_mcp_role", "Get an MCP role by ID with its entries. Each entry maps an MCP identity to tool glob patterns. Use after list_mcp_roles.", params!("id" => "MCP Role ID (UUID)"), &["id"]),
        tool!("overmind_create_mcp_role", "Create an MCP role. Roles are assigned to agents and contain entries that pair MCP identities with tool glob patterns.", params!("name" => "Unique role name", "description" => "Human-readable description of what this role grants"), &["name"]),
        tool!("overmind_update_mcp_role", "Update an MCP role's name or description. Use after get_mcp_role.", params!("id" => "MCP Role ID (UUID)", "name" => "Role name", "description" => "Role description"), &["id"]),
        tool!("overmind_delete_mcp_role", "Delete an MCP role. Fails if assigned to agents.", params!("id" => "MCP Role ID (UUID)"), &["id"]),
        tool!("overmind_create_mcp_role_entry", "Add an entry to an MCP role. Each entry grants access to an MCP identity's integration, optionally restricted by tool glob patterns.", params!("role_id" => "MCP Role ID (UUID)", "mcp_identity_id" => "MCP Identity ID to grant access to", "tool_globs" => "JSON array of tool name glob patterns. Empty means all tools."), &["role_id", "mcp_identity_id"]),
        tool!("overmind_update_mcp_role_entry", "Update an MCP role entry's identity or tool glob patterns. Use after get_mcp_role.", params!("role_id" => "MCP Role ID (UUID)", "entry_id" => "MCP Role Entry ID (UUID)", "mcp_identity_id" => "MCP Identity ID", "tool_globs" => "JSON array of tool name glob patterns"), &["role_id", "entry_id"]),
        tool!("overmind_delete_mcp_role_entry", "Remove an entry from an MCP role.", params!("role_id" => "MCP Role ID (UUID)", "entry_id" => "MCP Role Entry ID (UUID)"), &["role_id", "entry_id"]),
        tool!("overmind_list_pipelines", "List pipelines, optionally filtered by global context. Pipelines are legacy task-based workflows with ordered task definitions.", params!("global_context_id" => "Filter by Global Context ID (UUID)")),
        tool!("overmind_get_pipeline", "Get a pipeline by ID. Returns name, context, and global_context_id. Use after list_pipelines.", params!("id" => "Pipeline ID (UUID)"), &["id"]),
        tool!("overmind_create_pipeline", "Create a pipeline under a global context.", params!("name" => "Pipeline name", "global_context_id" => "Global Context ID (UUID)", "context" => "JSON context object with prompt, env, switchboard, and worktrees fields"), &["name", "global_context_id"]),
        tool!("overmind_update_pipeline", "Update a pipeline's name or context. Use after get_pipeline.", params!("id" => "Pipeline ID (UUID)", "name" => "Pipeline name", "context" => "JSON context object"), &["id"]),
        tool!("overmind_delete_pipeline", "Delete a pipeline.", params!("id" => "Pipeline ID (UUID)"), &["id"]),
        tool!("overmind_list_tasks", "List tasks for a pipeline. Tasks are individual work units with context and dependency ordering.", params!("pipeline_id" => "Pipeline ID (UUID)"), &["pipeline_id"]),
        tool!("overmind_get_task", "Get a task by ID. Returns name, context, pipeline_id, and depends_on list. Use after list_tasks.", params!("id" => "Task ID (UUID)"), &["id"]),
        tool!("overmind_create_task", "Create a task within a pipeline.", params!("name" => "Task name", "pipeline_id" => "Pipeline ID (UUID)", "context" => "JSON context object with prompt, env, switchboard, and worktrees fields", "depends_on" => "JSON array of task IDs this task depends on"), &["name", "pipeline_id"]),
        tool!("overmind_update_task", "Update a task's name, context, or dependencies. Use after get_task.", params!("id" => "Task ID (UUID)", "name" => "Task name", "context" => "JSON context object", "depends_on" => "JSON array of task IDs"), &["id"]),
        tool!("overmind_delete_task", "Delete a task from a pipeline.", params!("id" => "Task ID (UUID)"), &["id"]),
    ]
}
